name: Auto Publish Articles

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Trigger Auto Publish
        run: |
          curl -f "https://vintagenews.infinityfreeapp.com/script/cron-publish.php?secret=Andkfe9sdf8sdf8sdf8sdf8sdf8"